version: '3.8'

services:
  nginx-gateway:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../config/nginx:/etc/nginx/conf.d
      - ../../../nginx/nginx.conf:/etc/nginx/nginx.conf
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3